# noinspection PyUnresolvedReferences
from settings import DB, DB_PROXY, SYNC_OVERVIEW, DEBUG, TKINTER_TRACEBACK, \
    XLSX_FILE, BACKUP_FILE_FMT, CHECKBOX_FILE, CAMBRIDGE_BACKUP_DIR, CORPORA_BACKUP_DIR

HOST = 'mariadb101.websupport.sk'
PORT = 3312
USER = DB
PASSWD = 'lydkineblendy'

if DB_PROXY:
    HOST = '147.251.124.133'
    PORT = 443

CORP_HOST = HOST
CORP_PORT = PORT
CORP_USER = CORP_DB = 'corpus'
CORP_PASSWD = PASSWD

CAMBRIDGE_HOST = HOST
CAMBRIDGE_PORT = PORT
CAMBRIDGE_USER = CAMBRIDGE_DB = 'cambridge'
CAMBRIDGE_PASSWD = PASSWD

CORPORA_SLOVAK_SLEEP_TIME_ERROR = 20
CORPORA_SLOVAK_SLEEP_TIME_PREVENTIVE = 5

GENERATE_MULTITHREADED = True
